<a href="https://colab.research.google.com/github/vinosamari/learn-scikit/blob/master/SCIKIT_LEARN_101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install anaconda numba numpy pandas pandas-datareader patsy scikit-learn scipy statsmodels sympy

Scikit-learn addresses machine learning mainly via four categories:
- Classification
- Regression
- Clustering
- Dimensionality Reduction

**Classification asks**, *Is it an apple or an orange?* Contrast this with machine learning **Regression**, which asks, *How many apples?*


# **Numpy Basics**

In [23]:
import numpy as np

In [4]:
a1 = np.arange(10)

In [5]:
a1.shape

(10,)

In [6]:
a1 = a1.reshape(5,2) #CHANGES(RESHAPES) THE ARRAY TO 5 2-DIMENSIONAL ARRAYS

In [7]:
a1.shape

(5, 2)

In [8]:
a1.ndim #GETS THE NUMBER OF DIMENSIONS

2

### NUMPY BROADCASTING

The term broadcasting refers to the smaller array being stretched or broadcast across the larger array. In the following example, the scalar 1 will be stretched to a 5 x 2 shape and then added to a1.

In [16]:
a1_plus_one = a1 + 1

# SAME AS
# a1 + [[1 1]
#       [1 1]
#       [1 1]
#       [1 1]
#       [1 1]]

In [17]:
print(a1)
print(a1_plus_one)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [18]:
a2 = np.arange(10) #Here, element-wise multiplication will occur.
a2 = a2.reshape(5,2)
a2_plus_two = a2 ** 2 #Note that this is equivalent to a2 * a2
print(a2_plus_two)

[[ 0  1]
 [ 4  9]
 [16 25]
 [36 49]
 [64 81]]


In [20]:
a1_plus_one + a2_plus_two

array([[ 1,  3],
       [ 7, 13],
       [21, 31],
       [43, 57],
       [73, 91]])

In [14]:
one_by_five = np.arange(5).reshape(1,5)
print(one_by_five)

five_by_one = np.arange(5).reshape(5,1)
print(five_by_one)


[[0 1 2 3 4]]
[[0]
 [1]
 [2]
 [3]
 [4]]


In [15]:
weird_arr = one_by_five + five_by_one #ELEMENT TO ELEMENT ADDITION
print(weird_arr)

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


- The shapes of the arrays you're performing operations on are checked from RTL for a match (or mismatch).
- 5 x 2 and 5 x 2 = match
- 5 x 1 and 1 x 5 = match
- 1 x 2 and 2 x 1 = match
- 5 x 2 x 1 and 5 x 2 = mismatch
- 5 x 2 x 5 and 1 x 2 x 5 = match
- 1 x 2 x 5 and 1 x 5 x 2 = mismatch

As we can probably tell, the middle value from the right is compared for equality.

### Other numpy initialization methods include:

In [39]:
zeros = np.zeros((5,2))
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [43]:
#INITIALIZES ARRAY WITH 1s PASSING IN THE d-type ARGUMENT TO ENSURE THAT ALL ELEMENTS ARE INTEGERS (np.int)
#DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`.
# ones = np.ones((3,2), dtype=np.int) # <-- FROM THE BOOK. SAME GOES FOR FLOAT
#NOTE THAT SCIKIT EXPECTS float TYPES
ones = np.ones((3,2), dtype=int)
# ones = np.ones((3,2), dtype=float)
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])