<a href="https://colab.research.google.com/github/vinosamari/learn-scikit/blob/master/SCIKIT_LEARN_101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install anaconda numba numpy pandas pandas-datareader patsy scikit-learn scipy statsmodels sympy

Scikit-learn addresses machine learning mainly via four categories:
- Classification
- Regression
- Clustering
- Dimensionality Reduction

**Classification asks**, *Is it an apple or an orange?* Contrast this with machine learning **Regression**, which asks, *How many apples?*


# **Numpy Basics**

In [24]:
import numpy as np

In [25]:
a1 = np.arange(10)

In [26]:
a1.shape

(10,)

In [27]:
a1 = a1.reshape(5,2) #CHANGES(RESHAPES) THE ARRAY TO 5 2-DIMENSIONAL ARRAYS

In [28]:
a1.shape

(5, 2)

In [29]:
a1.ndim #GETS THE NUMBER OF DIMENSIONS

2

### NUMPY BROADCASTING

The term broadcasting refers to the smaller array being stretched or broadcast across the larger array. In the following example, the scalar 1 will be stretched to a 5 x 2 shape and then added to a1.

In [30]:
a1_plus_one = a1 + 1

In [31]:
print(a1)
print(a1_plus_one)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [41]:
a2 = np.arange(10)
a2 = a2.reshape(5,2)
print(a2 * a2)

[[ 0  1]
 [ 4  9]
 [16 25]
 [36 49]
 [64 81]]
